### GET a password be name
GET http://localhost:3333/api/passwords/Wifi

### POST a new password
POST http://localhost:3333/api/passwords
Content-Type: application/json

{   
    "name": "New",   
    "value": "super-secret-password"
}

### Delete password
DELETE http://localhost:3333/api/passwords/New